# Description:
#   Public Dagger API for Android

package(default_visibility = ["//visibility:public"])



android_library(
    name = "android",
    exports = [
        "//android/src/main/java/dagger/android",
    ],
)

